name:                Comb
version:             0.1.0.0
github:              "splintah/Comb"
license:             MIT
author:              "Splinter Suidman (splintah)"
copyright:           "2018 Splinter Suidman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/splintah/Comb#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  Comb-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Comb
    - HUnit
